load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("traffic_protocols")

cpp_unittest(
    name = "FizzTransportParametersTest",
    srcs = [
        "FizzTransportParametersTest.cpp",
    ],
    deps = [
        "//fizz/record/test:extension_tests_base",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//quic/common/test:test_utils",
        "//quic/fizz/handshake:fizz_handshake",
    ],
)

cpp_unittest(
    name = "FizzCryptoFactoryTest",
    srcs = [
        "FizzCryptoFactoryTest.cpp",
    ],
    deps = [
        "//fizz/crypto/aead/test:mocks",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//quic/common/test:test_utils",
        "//quic/fizz/handshake:fizz_handshake",
        "//quic/handshake/test:mocks",
    ],
)

cpp_unittest(
    name = "FizzPacketNumberCipherTest",
    srcs = [
        "FizzPacketNumberCipherTest.cpp",
    ],
    supports_static_listing = False,
    deps = [
        "//fizz/record:record",
        "//folly:string",
        "//folly/portability:gtest",
        "//quic/fizz/handshake:fizz_handshake",
    ],
)
