load("@fbcode//quic:defs.bzl", "mvfst_cpp_test")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("traffic_protocols")

mvfst_cpp_test(
    name = "FizzTransportParametersTest",
    srcs = [
        "FizzTransportParametersTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fizz/record/test:extension_tests_base",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//quic:constants",
        "//quic/common/test:test_utils",
        "//quic/fizz/handshake:fizz_handshake",
    ],
)

mvfst_cpp_test(
    name = "FizzCryptoFactoryTest",
    srcs = [
        "FizzCryptoFactoryTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fizz/crypto/aead/test:mocks",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//quic/common:string_utils",
        "//quic/common/test:test_utils",
        "//quic/fizz/handshake:fizz_handshake",
        "//quic/handshake/test:mocks",
    ],
)

mvfst_cpp_test(
    name = "FizzPacketNumberCipherTest",
    srcs = [
        "FizzPacketNumberCipherTest.cpp",
    ],
    network_access = network_access_utils.none(),
    supports_static_listing = False,
    deps = [
        "//fizz/record:record",
        "//folly/portability:gtest",
        "//quic/common:string_utils",
        "//quic/fizz/handshake:fizz_handshake",
    ],
)
