load("@fbcode//quic:defs.bzl", "mvfst_cpp_library")

oncall("traffic_protocols")

mvfst_cpp_library(
    name = "fizz_handshake",
    srcs = [
        "FizzBridge.cpp",
        "FizzCryptoFactory.cpp",
        "FizzPacketNumberCipher.cpp",
        "FizzRetryIntegrityTagGenerator.cpp",
        "QuicFizzFactory.cpp",
    ],
    headers = [
        "FizzBridge.h",
        "FizzCryptoFactory.h",
        "FizzPacketNumberCipher.h",
        "FizzRetryIntegrityTagGenerator.h",
        "FizzTransportParameters.h",
        "QuicFizzFactory.h",
    ],
    deps = [
        "//fizz/crypto:crypto",
        "//fizz/crypto:utils",
        "//quic/common:optional",
    ],
    exported_deps = [
        "//fizz/crypto/aead:aead",
        "//fizz/protocol:default_factory",
        "//fizz/protocol:types",
        "//fizz/record:record",
        "//folly/ssl:openssl_ptr_types",
        "//quic:constants",
        "//quic/codec:packet_number_cipher",
        "//quic/common:buf_util",
        "//quic/common:mvfst_logging",
        "//quic/folly_utils:folly_utils",
        "//quic/handshake:aead",
        "//quic/handshake:handshake",
        "//quic/handshake:retry_integrity_tag_generator",
        "//quic/handshake:transport_parameters",
    ] + select({
        "DEFAULT": [],
        "ovr_config//runtime/constraints:fbcode": select({
            "DEFAULT": ["fbcode//quic/facebook/handshake:xsec_crypto_bridge"],  # @fb-only
            "ovr_config//build_mode:arvr_mode": [],  # @fb-only
            "ovr_config//runtime/constraints:android-host-test": [],  # @fb-only
        }),  # @fb-only
    }),
)
