load("@fbcode//quic:defs.bzl", "mvfst_cpp_library")

oncall("traffic_protocols")

mvfst_cpp_library(
    name = "mu_connection",
    srcs = [
        "MuConnection.cpp",
    ],
    headers = [
        "MuConnection.h",
    ],
)
