load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

cpp_unittest(
    name = "fingerprint_test",
    srcs = ["QuicFingerprintTest.cpp"],
    deps = [
        "//quic/codec:types",
        "//quic/facebook/fingerprint:quicfingerprint",
        "//quic/handshake:transport_parameters",
    ],
)
