load("@fbcode//quic:defs.bzl", "mvfst_cpp_library")

oncall("traffic_protocols")

mvfst_cpp_library(
    name = "mocks",
    headers = [
        "Mocks.h",
    ],
    exported_deps = [
        "//folly:expected",
        "//folly:unit",
        "//folly/portability:gmock",
        "//quic:exception",
        "//quic/codec:packet_number_cipher",
        "//quic/fizz/handshake:fizz_handshake",
        "//quic/handshake:aead",
        "//quic/handshake:handshake",
    ],
)
