load("@fbcode//quic:defs.bzl", "mvfst_cpp_library")

oncall("traffic_protocols")

mvfst_cpp_library(
    name = "ttld_marker",
    srcs = [
        "TTLdMarker.cpp",
    ],
    headers = [
        "TTLdMarker.h",
    ],
    deps = [
        "//common/stats:thread_cached_service_data",
    ],
    exported_deps = [
        "//quic/api:transport",
        "//quic/congestion_control:packet_processor",
    ],
)

mvfst_cpp_library(
    name = "retransmits_scuba_reporter",
    srcs = [
        "RetransmitsScubaReporter.cpp",
    ],
    headers = [
        "RetransmitsScubaReporter.h",
    ],
    deps = [
        "//common/base:build_info",
        "//common/fbwhoami:fb_who_am_i",
        "//common/network:util",
        "//common/stats:thread_cached_service_data",
        "//configerator/distribution/common:ProcessNameUtils",
        "//justknobs:justknobs",
    ],
    exported_deps = [
        "//dsi/logger/configs/TcpRetransmitsAggregatorLoggerConfig:logger",
        "//quic/api:transport",
    ],
)
