load("@fbcode//quic:defs.bzl", "mvfst_cpp_test")

oncall("traffic_protocols")

mvfst_cpp_test(
    name = "StreamStateMachineTest",
    srcs = [
        "StreamStateMachineTest.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//quic/api:transport_helpers",
        "//quic/codec:types",
        "//quic/common/events:folly_eventbase",
        "//quic/common/test:test_utils",
        "//quic/fizz/server/handshake:fizz_server_handshake",
        "//quic/state/stream:stream",
    ],
)

mvfst_cpp_test(
    name = "StreamStateFunctionsTest",
    srcs = [
        "StreamStateFunctionsTest.cpp",
    ],
    deps = [
        "//quic/common/test:test_utils",
        "//quic/fizz/server/handshake:fizz_server_handshake",
        "//quic/logging:file_qlogger",
        "//quic/server/state:server",
        "//quic/state:stream_functions",
        "//quic/state/stream:stream",
    ],
)
