load("@fbcode//quic:defs.bzl", "mvfst_cpp_library")

oncall("traffic_protocols")

mvfst_cpp_library(
    name = "happyeyeballs",
    srcs = [
        "QuicHappyEyeballsFunctions.cpp",
    ],
    headers = [
        "QuicHappyEyeballsFunctions.h",
    ],
    deps = [
        "//common/network:mvfst_hooks",  # @manual
        "//folly:network_address",
        "//folly/portability:sockets",
        "//quic/common:socket_util",
        "//quic/state:quic_state_machine",
    ],
    exported_deps = [
        "//folly/io:socket_option_map",
        "//folly/net:net_ops",
        "//quic/client:state_and_handshake",
        "//quic/common/events:eventbase",
        "//quic/common/udpsocket:quic_async_udp_socket",
    ],
)
