load("@fbcode//quic:defs.bzl", "mvfst_cpp_test")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("traffic_protocols")

mvfst_cpp_test(
    name = "QuicFlowControlTest",
    srcs = [
        "QuicFlowControlTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//quic/client:state_and_handshake",
        "//quic/common/test:test_utils",
        "//quic/flowcontrol:flow_control",
        "//quic/state/test:mocks",
    ],
)
