load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("traffic_protocols")

cpp_unittest(
    name = "QuicFlowControlTest",
    srcs = [
        "QuicFlowControlTest.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//quic/client:state_and_handshake",
        "//quic/common/test:test_utils",
        "//quic/flowcontrol:flow_control",
        "//quic/state/test:mocks",
    ],
)
