load("@fbcode//quic:defs.bzl", "mvfst_cpp_library")

oncall("traffic_protocols")

mvfst_cpp_library(
    name = "flow_control",
    srcs = [
        "QuicFlowController.cpp",
    ],
    headers = ["QuicFlowController.h"],
    deps = [
        "//quic:constants",
        "//quic:exception",
        "//quic/logging:qlogger",
    ],
    exported_deps = [
        "//quic/codec:types",
        "//quic/state:quic_state_machine",
    ],
)
