load("@fbcode//quic:defs.bzl", "mvfst_cpp_library")
load("@fbsource//tools/build_defs:fb_xplat_cxx_library.bzl", "fb_xplat_cxx_library")

oncall("traffic_protocols")

mvfst_cpp_library(
    name = "mbed_aead",
    srcs = ["MbedAead.cpp"],
    headers = [
        "MbedAead.h",
    ],
    exported_deps = [
        "fbsource//xplat/mobilenetwork/third-party/mbedtls:tls",  # @manual
        "//fizz/crypto/aead:cryptoutil",
        "//quic/handshake:aead",
    ],
    external_deps = [
        "glog",
    ],
)

mvfst_cpp_library(
    name = "mbed_packetnum_cipher",
    srcs = [
        "MbedPacketNumCipher.cpp",
    ],
    headers = [
        "MbedPacketNumCipher.h",
    ],
    exported_deps = [
        "fbsource//xplat/mobilenetwork/third-party/mbedtls:tls",  # @manual
        ":mbed_aead",
        "//quic/codec:packet_number_cipher",
    ],
)

mvfst_cpp_library(
    name = "mbed_handshake",
    srcs = [
        "MbedCryptoFactory.cpp",
    ],
    headers = [
        "MbedCryptoFactory.h",
    ],
    deps = [
        ":mbed_packetnum_cipher",
    ],
    exported_deps = [
        "fbsource//xplat/mobilenetwork/third-party/mbedtls:tls",  # @manual
        ":mbed_aead",
        "//quic/handshake:handshake",
    ],
    external_deps = [
        "glog",
    ],
)

fb_xplat_cxx_library(
    name = "mbed_client_handshake",
    srcs = [
        "MbedClientHandshake.cpp",
    ],
    header_namespace = "quic/facebook/mbed",
    exported_headers = [
        "MbedClientHandshake.h",
    ],
    compatible_with = ["ovr_config//os:linux"],
    compiler_flags = ["-Wno-c++98-compat-pedantic"],
    visibility = ["PUBLIC"],
    deps = [
        "fbsource//xplat/mobilenetwork/third-party/mbedtls:tls",  # @manual
        ":mbed_handshake",
        "//quic/client:cached_server_tp",
        "//quic/client:client_extension",
        "//quic/client:state_and_handshake",
        "//quic/handshake:transport_parameters",
    ],
    exported_deps = [
        "fbsource//xplat/mobilenetwork:quiccommon",
        "fbsource//xplat/mobilenetwork:tls_mbed",  # @manual
    ],
)

fb_xplat_cxx_library(
    name = "mbed_client_handshake_factory",
    srcs = ["MbedClientHandshakeFactory.cpp"],
    header_namespace = "quic/facebook/mbed",
    exported_headers = ["MbedClientHandshakeFactory.h"],
    compatible_with = ["ovr_config//os:linux"],
    compiler_flags = ["-Wno-c++98-compat-pedantic"],
    visibility = ["PUBLIC"],
    deps = [
        ":mbed_client_handshake",
        "//quic/client:state_and_handshake",
    ],
)
