load("@fbcode//quic:defs.bzl", "mvfst_cpp_test")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("traffic_protocols")

mvfst_cpp_test(
    name = "SocketObserverInterfaceTest",
    srcs = [
        "SocketObserverInterfaceTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//quic/common/test:test_packet_builders",
        "//quic/common/test:test_utils",
        "//quic/observer:socket_observer_interface",
    ],
)
