load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("traffic_protocols")

cpp_unittest(
    name = "PacingObserverTest",
    srcs = [
        "PacingObserverTest.cpp",
    ],
    deps = [
        "//quic/common/test:test_utils",
        "//quic/logging/test:mocks",
        "//quic/tools/tperf:pacing_observer",
    ],
)
