load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("traffic_protocols")

cpp_binary(
    name = "mu_sample",
    srcs = [
        "MuSample.cpp",
    ],
    headers = [
        "MuSample.h",
    ],
    deps = [
        "//quic/facebook/mu/connection:mu_connection",
    ],
)
