load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs:fb_xplat_cxx_test.bzl", "fb_xplat_cxx_test")
load("@fbsource//tools/build_defs:platform_defs.bzl", "CXX")

oncall("traffic_protocols")

cpp_unittest(
    name = "aead",
    srcs = ["Aead.cpp"],
    supports_static_listing = False,
    deps = [
        "//fizz/crypto/aead/test:test_util",
        "//folly/portability:gtest",
        "//quic/facebook/mbed:mbed_aead",
    ],
)

cpp_unittest(
    name = "packetnum_cipher",
    srcs = ["PacketNumCipher.cpp"],
    supports_static_listing = False,
    deps = [
        "//folly:random",
        "//folly:string",
        "//folly/portability:gtest",
        "//quic/facebook/mbed:mbed_packetnum_cipher",
    ],
)

cpp_unittest(
    name = "crypto_factory",
    srcs = ["CryptoFactory.cpp"],
    deps = [
        "//fizz/crypto/aead/test:test_util",
        "//folly/portability:gtest",
        "//quic/facebook/mbed:mbed_handshake",
        "//quic/fizz/handshake:fizz_handshake",
    ],
)

fb_xplat_cxx_test(
    name = "mbed_client_handshake",
    srcs = ["MbedClientHandshake.cpp"],
    headers = [],
    header_namespace = "",
    compatible_with = ["ovr_config//os:linux"],
    compiler_flags = ["-Wno-c++98-compat-pedantic"],
    platforms = [CXX],
    deps = [
        "//fizz/crypto/aead/test:test_util",
        "//fizz/record:record",
        "//folly/executors:manual_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//quic/common/test:test_utils",
        "//quic/facebook/mbed:mbed_client_handshake",
        "//quic/facebook/mbed:mbed_client_handshake_factory",
        "//quic/fizz/client/handshake:fizz_client_handshake",
        "//quic/fizz/handshake:fizz_handshake",
        "//quic/fizz/server/handshake:fizz_server_handshake",
        "//quic/server/handshake:server_extension",
        "//quic/server/state:server",
    ],
)
