load("@fbcode//quic:defs.bzl", "mvfst_cpp_test")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("traffic_protocols")

mvfst_cpp_test(
    name = "DatagramFlowManagerTest",
    srcs = [
        "DatagramFlowManagerTest.cpp",
    ],
    network_access = network_access_utils.none(),
    supports_static_listing = False,
    deps = [
        "//folly/portability:gtest",
        "//quic/datagram:datagram_flow_manager",
        "//quic/priority:http_priority_queue",
    ],
)
